from django.conf import settings


CHARGEABLE_STRIPE_MINIMUM_CHARGE_AMOUNT = getattr(settings, 'CHARGEABLE_STRIPE_MINIMUM_CHARGE_AMOUNT', 50)
CHARGEABLE_STRIPE_MAXIMUM_CHARGE_AMOUNT = getattr(settings, 'CHARGEABLE_STRIPE_MAXIMUM_CHARGE_AMOUNT', 50000)
CHARGEABLE_CHARGE_LOCK_TIME = getattr(settings, 'CHARGEABLE_CHARGE_LOCK_TIME', 60)